kind: pipeline
name: sooty-tern-prod

workspace:
  base: /root
  path: web/sooty-tern

steps:
  - name: build
    image: golang
    commands:
      - CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o sooty-tern cmd/server/main.go 
    environment:
      GOPROXY: https://goproxy.io
      GO111MODULE: on

  - name: publish
    image: plugins/docker
    settings:
      registry: registry.cn-beijing.aliyuncs.com
      repo: registry.cn-beijing.aliyuncs.com/meichaofan/sooty-tern
      dockerfile: ./Dockerfile
      Username:
        from_secret: docker_username
      Password:
        from_secret: docker_password
      tags: prod
      build_args:
        - SOOTY_TERN_ENV=prod

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      script:
        - cd /root/web/sooty-tern
        - docker login --username=15652908216 registry.cn-beijing.aliyuncs.com -p huanhuan0921
        - docker-compose pull sooty-tern
        - docker-compose up -d

trigger:
  branch:
    - master
  event:
    - pull_request

---
kind: pipeline
name: sooty-tern-test

workspace:
  base: /root
  path: web/sooty-tern

steps:
  - name: build
    image: golang
    commands:
      - CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o sooty-tern cmd/server/main.go
    environment:
      GOPROXY: https://goproxy.io
      GO111MODULE: on

  - name: publish
    image: plugins/docker
    settings:
      registry: registry.cn-beijing.aliyuncs.com
      repo: registry.cn-beijing.aliyuncs.com/meichaofan/sooty-tern
      dockerfile: ./Dockerfile
      Username:
        from_secret: docker_username
      Password:
        from_secret: docker_password
      tags: test
      build_args:
        - SOOTY_TERN_ENV=test

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host_test
      username:
        from_secret: ssh_username_test
      password:
        from_secret: ssh_password_test
      port:
        from_secret: ssh_port_test
      script:
        - cd /root/sooty-tern
        - docker login --username=15652908216 registry.cn-beijing.aliyuncs.com -p huanhuan0921
        - docker-compose pull sooty-tern
        - docker-compose up -d

trigger:
  branch:
    - test
  event:
    - push

---
kind: pipeline
name: sooty-tern-dev

workspace:
  base: /root
  path: web/sooty-tern

steps:
  - name: build
    image: golang
    commands:
      - CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o sooty-tern cmd/server/main.go
    environment:
      GOPROXY: https://goproxy.io
      GO111MODULE: on

  - name: publish
    image: plugins/docker
    settings:
      registry: registry.cn-beijing.aliyuncs.com
      repo: registry.cn-beijing.aliyuncs.com/meichaofan/sooty-tern
      dockerfile: ./Dockerfile
      Username:
        from_secret: docker_username
      Password:
        from_secret: docker_password
      tags: dev
      build_args:
        - SOOTY_TERN_ENV=dev

trigger:
  branch:
    - dev
  event:
    - push
