version: '3.5'
networks:
  backend:
    name: sooty_tern_back
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.7.0/24
services:
  sooty-tern:
    image: meichaofan/sooty-tern:dev
    container_name: sooty-tern
    ports:
      - "10080:8080"
    networks:
      - backend
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=huanhuan0921
    volumes:
      - ./data/mysql:/var/lib/mysql
    container_name: lz_mysql
    networks:
      - backend
  redis:
    image: redis:5.0
    volumes:
      - ./data/redis:/data
    container_name: lz_redis
    networks:
      - backend
